//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.StopStations = new HashSet<StopStation>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int ID { get; set; }
        public string Price { get; set; }
        public System.DateTime StarTime { get; set; }
        public int DepartmentID { get; set; }
        public int DestinationtID { get; set; }
        public int EstimateDistance { get; set; }
        public int BusID { get; set; }
        public System.DateTime EstimateArrivalTime { get; set; }
        public int EstimatePassenger { get; set; }
        public string Status { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Departure Departure { get; set; }
        public virtual Destination Destination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StopStation> StopStations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
