//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID { get; set; }
        public string TicketCode { get; set; }
        public int UserID { get; set; }
        public decimal Price { get; set; }
        public System.DateTime TicketCreateDate { get; set; }
        public System.DateTime TicketExpiredDate { get; set; }
        public int RouteID { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual User User { get; set; }
    }
}
